name: Hugo Deploy GitHub Pages
  # You may pin to the exact commit or the version.
  # uses: benmatselby/hugo-deploy-gh-pages@7c17fd574c2d6a3308cc2b0e433e99e9c2e454b5
  uses: benmatselby/hugo-deploy-gh-pages@v1.12.0
  with:
    # The version of hugo to use.
    hugo_version: 
    # If set to `true`, use the *extended* version of hugo.
    hugo_extended: # optional
    # Your PAT to authorise the action to do things.
    github_token: 
    # The repo name you want to clone and push to.
    target_repo: 
    # The branch to push the hugo public files, default will be master branch.
    target_branch: # optional
    # Any extra arguments to pass to Hugo.
    hugo_args: # optional
    # If you are defining a custom domain name for your GitHub site, put that value in this variable.
    cname: # optional
